# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title:            Intermittent Fasting Pro
tagline:          'The IF Wiki'
description:      'A wiki that collects all the facts about intermittent fasting in one place.'
url:              http://intermittentfasting.pro/
baseurl:          /

google_site_verification: UP5h0gTVVBwalSmRxt-yS6L5c3CdV1RGzzAsGI5SHdw

author:
  name:           'Jono Shields'

include:           ["_pages"]

gems:             ['jekyll-gist', 'jekyll-seo-tag']
