# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Intermittent Fasting (IF)
tagline:          'A Jekyll theme'
description:      'All the facts about intermittent fasting in one place.'
url:              http://foopod.github.io/intermittentFasting

author:
  name:           'Jono Shields'
  url:            https://twitter.com/foocodes

gems:             ['jekyll-gist']