# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Intermittent Fasting Pro
tagline:          'A Jekyll theme'
description:      'All the facts about intermittent fasting in one place.'
url:              http://intermittentfasting.pro/
baseurl:          /

author:
  name:           'Jono Shields'
  url:            https://twitter.com/foocodes

gems:             ['jekyll-gist']
